version: "3.9"
services:
  postgresql:
    image: "postgres:14.1-alpine"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
      POSTGRES_DB: wallet
    networks:
      - backend

networks:
  backend:

volumes:
  pg_data:

